### ISSUE TITLE
Log-in/Lost password

### ISSUE THREAD

**Issue by IronRunes** [level73/membernet#1]
The field asks for the insertion of an email account, but displays incorrect email even though it is correct (system doesnt work) & furthermore members dont know which email account we've set them up with

**Comment by decasadecasa** [comment]
furthermore Both lost password and request account lead to same page/text

**Comment by IronRunes** [comment]
@decasadecasa How would we want to manage the request account feature? The process can be automated only to the extent of the request, not the actual account creation (because how could we verify account requests belonging to orgs consistently without human interaction?)

**Comment by IronRunes** [comment]
I fixed the error that wouldn't match the request to existing emails - Still need to fix the "reset" functionality

**Comment by decasadecasa** [comment]
Yes, sorry if my wording was misleading, obviously we can't automate the actual account creation. The issue I was referring to is that since we created their accounts, they don't know which email we've signed them up with (its usually the email of the focal point of organization), so they can't request the password reset unless we inform them of their email account before hand. Could we perhaps make the field ask for the organizational name when prompting the recovery, stating please insert the focal point email? Its not very ideal but I can't think of another solution. Please let me know if you have any suggestions how to go about this. If we get the request account feature functioning then perhaps this will help.

**Comment by IronRunes** [comment]
Password recovery has been fixed. I created another issue for the account requests - #19

**Comment by decasadecasa** [comment]
@IronRunes Hi! I tried to recover the password using my old account email (landcoalition email), it prompted me saying the email was sent but I did not get it in my inbox/spam folder.

**Comment by exhej11** [comment]
![Capture](https://user-images.githubusercontent.com/48788375/55221032-ec594480-5208-11e9-9909-68e0756c8027.PNG)

The recover password works with a gmail account but not with our work emails.

**Comment by IronRunes** [comment]
we'll need to: 

1. setup a proper email account for Membernet (something like membernet[at]landcoalition, a gmail account is fine)
2. ask the people in IT in your offices to accept emails from the system. 

this is pretty much out of my power of resolution, so I'll close the issue. :)

**Comment by decasadecasa** [comment]
If we were to make the membernet email with a landcoalition account instead of gmail, are there implications for this? 

Could you also please advise on what to write to IT regarding the acceptance of emails? Many thanks
