### ISSUE TITLE
Membership Fees not displaying all results when searched by year in general search

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#41]
![membershipfeeserror](https://user-images.githubusercontent.com/40179449/55956370-1af10980-5c64-11e9-832d-2221af44a983.PNG)

As you can see here only 2 results show up for the year 2018

**Comment by IronRunes** [comment]
this one is tricky to explain. 
theoretically, when searching by year, you shouldn't get any results at all in the membership fee list. that is because membership fees are not tagged by year, as they have an ongoing year-based flag field in the entity - plus. they do not refer to happening in a specific year. 
the fact that we have 2 results showing up when searching by year is a bug - bu its related to the metadata being attached to the record, rather than not displaying data that should. 
I hope that was clarifying. :) 
feel free to close the issue if that was ok, happy to discuss further if need be. :)

**Comment by decasadecasa** [comment]
thanks for this! Could you just advise what needs to be done in the back end to stop those 2 from appearing? Then we can close this issue. Cheers

**Comment by IronRunes** [comment]
i unset the association to the "year" meta layer and everything went fine.
